# Generated by Django 6.0.5 on 2026-09-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerseasonscore',
            name='achievement_breakdown',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='playerseasonscore',
            name='achievement_score',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
    ]
