# Generated by Django 6.0.5 on 2026-09-30 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_competitionseason_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=30, unique=True)),
                ('config', models.JSONField()),
                ('checksum_sha256', models.CharField(editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='competition',
            name='format',
            field=models.CharField(choices=[('LEAGUE', 'League'), ('CUP', 'Cup'), ('UNKNOWN', 'Unclassified')], default='UNKNOWN', max_length=10),
        ),
        migrations.AddField(
            model_name='competition',
            name='participant_type',
            field=models.CharField(choices=[('CLUB', 'Clubs'), ('NATIONAL', 'National teams'), ('UNKNOWN', 'Unclassified')], default='UNKNOWN', max_length=10),
        ),
        migrations.AddField(
            model_name='competition',
            name='scope',
            field=models.CharField(choices=[('DOMESTIC', 'Domestic'), ('CONTINENTAL', 'Continental'), ('GLOBAL', 'Global'), ('UNKNOWN', 'Unclassified')], default='UNKNOWN', max_length=15),
        ),
        migrations.AddField(
            model_name='competitionseason',
            name='edition_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='competitionseason',
            name='ends_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competitionseason',
            name='starts_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixture',
            name='available_minutes',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixture',
            name='neutral_venue',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='competition',
            name='competition_type',
            field=models.CharField(choices=[('DOMESTIC_LEAGUE', 'Domestic league'), ('UCL', 'UEFA Champions League'), ('CUP', 'Other tournament'), ('UNKNOWN', 'Unclassified')], max_length=30),
        ),
        migrations.AddField(
            model_name='competitionseason',
            name='context_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='football.campaignpolicy'),
        ),
        migrations.CreateModel(
            name='WinningCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('awarded_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('evidence', models.TextField(blank=True)),
                ('expected_matches', models.PositiveSmallIntegerField()),
                ('is_complete', models.BooleanField(default=False)),
                ('edition', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='winning_campaign', to='football.competitionseason')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='football.campaignpolicy')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='football.team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerCampaignContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of', models.DateTimeField()),
                ('contribution', models.DecimalField(blank=True, decimal_places=10, max_digits=12, null=True)),
                ('reason', models.CharField(blank=True, max_length=100)),
                ('breakdown', models.JSONField()),
                ('input_sha256', models.CharField(max_length=64)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaign_contributions', to='football.player')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='football.winningcampaign')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('campaign', 'player', 'as_of', 'input_sha256'), name='uniq_campaign_contribution_input')],
            },
        ),
    ]
