# Generated by Django 6.0.5 on 2026-09-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0003_campaignpolicy_competition_format_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='competitionseason',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_season_id__isnull', False), models.Q(('provider_season_id', ''), _negated=True)), fields=('competition', 'provider_season_id'), name='uniq_provider_competition_edition'),
        ),
    ]
