# Generated by Django 6.0.5 on 2026-09-30 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0005_existing_competition_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='award_season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='awarded_fixtures', to='football.season'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='player_data_unavailable_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
