# Generated by Django 6.0.5 on 2026-09-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankingsnapshot',
            name='coverage_summary',
            field=models.JSONField(default=dict),
        ),
    ]
