# Generated by Django 6.0.5 on 2026-10-01 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0006_fixture_award_season_and_more'),
        ('ingestion', '0005_reviewed_positions_and_identity_aliases'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixtureStatReconstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('source_provider', models.CharField(max_length=30)),
                ('source_fixture_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PARTIAL', 'Partial evidence'), ('VERIFIED', 'Verified'), ('APPLIED', 'Applied')], max_length=20)),
                ('normalized_payload', models.JSONField()),
                ('verification', models.JSONField()),
                ('payload_sha256', models.CharField(max_length=64)),
                ('raw_payload_ids', models.JSONField(default=list)),
                ('staged_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stat_reconstructions', to='football.fixture')),
            ],
            options={
                'indexes': [models.Index(fields=['version', 'status'], name='ingestion_f_version_0c170b_idx')],
                'constraints': [models.UniqueConstraint(fields=('version', 'fixture'), name='uniq_fixture_reconstruction_version')],
            },
        ),
    ]
